services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      TESLACAM_ROOT: /data/TeslaCam
    ports:
      - "8765:8080"
    volumes:
      - ${TESLACAM_PATH:-./data/TeslaCam}:/data/TeslaCam:ro
      - ./data/Thumbnails:/data/Thumbnails
      - ./data/Previews:/data/Previews
    restart: unless-stopped
